baseURL = "http://example.org/"
languageCode = "el-gr"
title = "giannoug's blog"
description = "Î™ÏƒÏ„Î¿ÏÎ¯ÎµÏ‚ software ÎºÎ±Î¹ hardware engineering"
paginate = 5
theme = "PaperMod"

[markup.goldmark.renderer]
unsafe = true

[params]
title = "giannoug's blog"
description = "Î™ÏƒÏ„Î¿ÏÎ¯ÎµÏ‚ software ÎºÎ±Î¹ hardware engineering"
author = "giannoug"

[params.homeInfoParams]
Title = "ÎšÎ±Î»Ï‰ÏƒÎ®ÏÎ¸ÎµÏ‚ ğŸ‘‹"
Content = "Î¤Î¿ Ï€ÎµÏÎ¹ÎµÏ‡ÏŒÎ¼ÎµÎ½Î¿ Ï„Î¿Ï… blog Î´Î·Î¼Î¿ÏƒÎ¹ÎµÏÏ„Î·ÎºÎµ ÏƒÏ‡ÎµÎ´ÏŒÎ½ Î¼Î¹Î± Î´ÎµÎºÎ±ÎµÏ„Î¯Î± Ï€ÏÎ¹Î½ ÎºÎ±Î¹ Ï€Î¹Î¸Î±Î½ÏÏ‚ Î½Î± Ï€ÎµÏÎ¹Î­Ï‡ÎµÎ¹ Î¹Î´Î­ÎµÏ‚, Î±Ï€ÏŒÏˆÎµÎ¹Ï‚ ÎºÎ±Î¹ ÏÏ†Î¿Ï‚ Ï€Î¿Ï… Î´ÎµÎ½ Î¼Îµ ÎµÎºÏ†ÏÎ¬Î¶Î¿Ï…Î½ Ï€Î»Î­Î¿Î½"

[[menu.main]]
identifier = "home"
name = "Î‘ÏÏ‡Î¹ÎºÎ®"
url = "/"
weight = 10

[[menu.main]]
identifier = "about"
name = "About"
url = "/about/"
weight = 20